export const teamsData = [
    {
        team: 'San Lorenzo',
        shield: <img src="/assets/img/futbol-icons/teams/sanlorenzo.png" alt="sanlorenzo"></img>,
        pts: '8',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Union',
        shield: <img src="/assets/img/futbol-icons/teams/union.png" alt="union"></img>,
        pts: '6',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Talleres',
        shield: <img src="/assets/img/futbol-icons/teams/talleres.png" alt="talleres"></img>,
        pts: '13',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Banfield',
        shield: <img src="/assets/img/futbol-icons/teams/banfield.png" alt="banfield"></img>,
        pts: '8',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Estudiantes',
        shield: <img src="/assets/img/futbol-icons/teams/estudiantes.png" alt="estudiantes"></img>,
        pts: '13',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Patronato',
        shield: <img src="/assets/img/futbol-icons/teams/patronato.png" alt="patronato"></img>,
        pts: '12',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Argentinos',
        shield: <img src="/assets/img/futbol-icons/teams/argentinos.png" alt="argentinos"></img>,
        pts: '12',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Racing',
        shield: <img src="/assets/img/futbol-icons/teams/racing.png" alt="racing"></img>,
        pts: '14',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Def. y Justicia',
        shield: <img src="/assets/img/futbol-icons/teams/defensa.png" alt="defensa"></img>,
        pts: '8',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Platense',
        shield: <img src="/assets/img/futbol-icons/teams/platense.png" alt="platense"></img>,
        pts: '6',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Rosario Central',
        shield: <img src="/assets/img/futbol-icons/teams/central.png" alt="central"></img>,
        pts: '4',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Arsenal',
        shield: <img src="/assets/img/futbol-icons/teams/arsenal.png" alt="arsenal"></img>,
        pts: '5',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Boca',
        shield: <img src="/assets/img/futbol-icons/teams/boca.png" alt="boca"></img>,
        pts: '7',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'River',
        shield: <img src="/assets/img/futbol-icons/teams/river.png" alt="river"></img>,
        pts: '11',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Independiente',
        shield: <img src="/assets/img/futbol-icons/teams/independiente.png" alt="independiente"></img>,
        pts: '15',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Central Cba',
        shield: <img src="/assets/img/futbol-icons/teams/centralcordoba.png" alt="centralcordoba"></img>,
        pts: '6',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Velez',
        shield: <img src="/assets/img/futbol-icons/teams/velez.png" alt="velez"></img>,
        pts: '6',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Sarmiento',
        shield: <img src="/assets/img/futbol-icons/teams/sarmiento.png" alt="sarmiento"></img>,
        pts: '10',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Newells',
        shield: <img src="/assets/img/futbol-icons/teams/newells.png" alt="newells"></img>,
        pts: '11',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Aldosivi',
        shield: <img src="/assets/img/futbol-icons/teams/aldosivi.png" alt="aldosivi"></img>,
        pts: '13',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Colon',
        shield: <img src="/assets/img/futbol-icons/teams/colon.png" alt="colon"></img>,
        pts: '14',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Gimnasia',
        shield: <img src="/assets/img/futbol-icons/teams/gimnasia.png" alt="gimnasia"></img>,
        pts: '9',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Huracan',
        shield: <img src="/assets/img/futbol-icons/teams/huracan.png" alt="huracan"></img>,
        pts: '7',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Godoy Cruz',
        shield: <img src="/assets/img/futbol-icons/teams/godoycruz.png" alt="godoycruz"></img>,
        pts: '10',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Lanus',
        shield: <img src="/assets/img/futbol-icons/teams/lanus.png" alt="lanus"></img>,
        pts: '13',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    },
    {
        team: 'Atl. Tucuman',
        shield: <img src="/assets/img/futbol-icons/teams/tucuman.png" alt="tucuman"></img>,
        pts: '8',
        pj:'4',
        pg: '3',
        pe: '0',
        pp: '0',
        gf: '5',
        gc: '2',
        dif: '3'
    }
]