module.exports = boca = [
    {
        title: "Buena noticia para Battaglia a horas del Súper",
        description: "Agustín Almendra se entrenó a la par pese a sus molestias musculares.",
        content: "No es algo menor recibir buenas noticias a horas de un superclásico. Y eso es lo que le pasó a Sebastián Battaglia este viernes en el anteúltimo entrenamiento de Boca de cara al partido con River: el entrenador pudo contar con Agustín Almendra, quien había terminado con molestias musculares el día anterior. La alarma había sonado en el Complejo de Ezeiza cuando el jueves Almendra no pudo terminar el ensayo de fútbol formal que propuso Battaglia. ¿Qué le pasó? Una fuerte molestia muscular que no le permitió finalizar la actividad y por la que fue reemplazado por Aaron Molinas. Pese a la preocupación, la primera reacción del CT de Battaglia fue esperar para saber cómo evolucionaba, sobre todo este viernes, ya que es un día determinante para el entrenador porque por lo general dos días antes de los partidos es cuando define quiénes serán los concentrados. Y allí la buena noticia de la mañana soleada de Ezeiza: Almendra no sólo trabajó a la par del grupo, sino que además no mostró secuelas de la dolencia que tuvo el jueves. Ojo, más allá de que seguramente el mediocampista de 21 años forme parte de los concentrados de Battaglia. Esto sin dudas que le resuelve un problemón al técnico de Boca, ya que ve en Almendra un futbolista que le cumple una doble función. El juvenil, que ya tiene 54 partidos en el Xeneize (y tres goles), cumple con los requisitos de volante mixto que busca el León, que encuentra en Agustín marca, equilibrio y una rueda de auxilio para Jorman Campuzano; pero además también visión de juego en ataque, asistencias y gol.",
        urlToImage: "https://images.ole.com.ar/2021/09/21/kP0xGTNzL_1256x620__3.jpg#1633099678544"
    },
    {
        title: "Valentín Barco: no look, golazo y Topo Gigio a River en Ezeiza",
        description: "El Colo arrancó en su propio campo y terminó festejando de cara al público.",
        content: "La jugada arrancó en su propio campo, con una pelota recuperada por él y una pisadita entre dos rivales. Avanzó unos metros, abrió hacia la izquierda para Zeballos con un pase no look y fue a buscar la devolución al área, donde recibió y sacó un zurdazo cruzado para anotar el 3-0 a River como visitante en Ezeiza. Valentín Barco es cosa seria. Y luego, a la hora del festejo, el lateral izquierdo la hizo completa con una corrida hacia una tribuna, freno y festejo en modo Topo Gigio y pedido de silencio de cara al público llevándose el dedo a la boca. A lo Juan Román Riquelme, ídolo y vicepresidente xeneize. Por un lado, provocador y desafiante, cero fair play en un partido que tuvo momentos calientes entre los chicos. Y por otro, desubicado que desde la tribuna, al igual que pasa en Primera, los 'allegados' insulten y hostiguen a los futbolistas. El desahogo volvió a darse al final, en el medio de la cancha, con todo el equipo cantando. 'Porque los jugadores me van a demostrar, que salen a ganar, quieren salir campeo, que lo llevan adentro como lo llevo yo...', gritaron los pibes xeneizes.",
        urlToImage: "https://images.ole.com.ar/2021/10/01/1nR1_9fO3_1256x620__2.jpg#1633101634734"
    },
    {
        title: "El triple desafío de Orsini contra River",
        description: "El cordobés, titular este domingo en el Monumental, vivirá una tarde más que especial. Mirá...",
        content: "Un abuelo era bostero. El otro, gallina. Entonces, no era extraño ver al pequeño Nicolás patear las calles de Morteros, al noreste de Córdoba, con la camiseta de Boca y el pantaloncito de River. Hasta que a allá por 1998, cuando tenía cinco años, decidió pintarse el flequillo de amarillo a lo Martín Palermo. Hoy, Nico tiene 27, juega en Boca y cumplirá el sueño de disputar su primer superclásico. Será, de hecho, el único futbolista xeneize que tendrá su primera vez ante el Millo. Nicolás Orsini es, actualmente, el 9 titular del equipo de Battaglia. Un puesto que parecía tener dueño (el pibe Luis Vázquez), pero en el que el DT prefiere, por lo visto, gente de mayor experiencia. Y Orsini aprovechó su chance. Aunque le costó convertir (un tanto en ocho partidos), pudo sacarse la mufa ante Colón, justo en la previa del clásico. 'Venía teniendo situaciones, que para un 9 es importante, pero no la podía meter. A veces le pegás con el tobillo y entra, a veces le pegás bien y te la saca el arquero. Ojalá el arco se quede abierto para el clásico', había deseado el ex Lanús luego del triunfo 1-0 ante el Sabalero.",
        urlToImage: "https://images.ole.com.ar/2021/10/02/O7Cj7U3O6_1256x620__2.jpg#1633198780244"
    },
    {
        title: "Márcico: “El estilo de Battaglia puede ayudar a ellos”",
        description: "El Beto marcó diferencias entre el actual DT y Russo. “El fuerte de Miguel era no hacerlo jugar bien a River”.",
        content: "Alberto Márcico, más conocido por los hinchas Xeneizes como el Beto, a pocos días del Superclásico, elogió a Sebastián Battaglia por su buen momento futbolístico. Pero también hizo hincapié y reconoció que cree la idea de juego del actual técnico de Boca puede llegar a beneficiar a River. También habló sobre la posible llegada de Marcelo Gallardo al Barcelona y contó quién es el mejor jugador del fútbol argentino. Con respecto a la problemática que puede llegar a generar el modo de juego de Battaglia dijo: “Me preocupa que su propuesta los ayude a ellos a jugar mejor”, aseguró el ex Boca por el programa radial Súper Deportivo Radio por Radio Villa Trinidad. Beto siguió haciendo un análisis sobre la situación actual del Xeneize y trazó un paralelismo con el Boca de Miguel Angel Russo. 'Miguel le había encontrado la vuelta a River: lo eliminó dos veces, no perdió nunca y le sacó un campeonato que River lo tenía en el buche. El fuerte de Miguel era no hacerlo jugar bien a River. Era especialista en eso y lo dejó afuera tres veces'. Con respecto al futuro de Battaglia y al superclásico, fue contundente. “A Sebastián lo confirmaría en el cargo. El domingo será un partido muy parejo. Boca triangula y tiene un juego de equipo. Cuenta con la mejor defensa del fútbol argentino y al cuarto arquero de la Selección”, manifestó. El tres veces campeón con el Xeneize indicó que “el domingo hay que mantener la idea, porque River no está bien atrás y le generan muchas situaciones de gol”. En tanto, añadió: “Ellos son intensos y están bien de la mitad para adelante. Tienen al mejor jugador del país, que es Julián Álvarez” y finalmente destacó a Gallardo como un excelente técnico.",
        urlToImage: "https://images.ole.com.ar/2021/10/01/mXMzSejxW_1256x620__2.jpg#1633107450054"
    }
]