module.exports = health = [
    {
        title: "Ideal para mantener la calma y relajar el cuerpo ¡prueba la infusión de valeriana!",
        description: "Si estás notando que te cuesta relajarte y aprovechar las horas de descanso, será cuestión que cheques la información que hoy te compartiremos.",
        content: "Esta planta medicinal es un tranquilizante natural, la valeriana es muy utilizada cuando uno padece trastornos del sueño o insomnio. El nombre científico es Valeriana Officinalis, aunque si vas a una tienda naturista, dietética o herboristería lo encontrarás como popularmente se la llama 'Valeriana'. Esta planta proviene de Europa y Asia, si bien se ha popularizado y se consigue con facilidad; al día de hoy existen plantaciones en distintos puntos como en India, Chile; Japón, Colombia, Bélgica, entre otros. La valeriana es un gran aliado como tranquilizante y sedante sobre el cuerpo. Otro de los beneficios que encontrarás en esta planta medicinal, es muy eficiente en calmar la tos y colabora la salud del corazón. Con el pasar de los días, notarás que te alivia el estrés y colabora a conciliar un sueño profundo. También se pueden combinar con otras hierbas, como con eucalipto y conseguir más beneficios para tratar resfriados o congestiones. A la hora de preparar esta infusión solo necesitarás una cucharada de raíz de valeriana, luego agregamos el agua fría o tibia, dejamos reposar durante toda la noche y luego la bebemos, puedes endulzarla con azúcar, miel o stevia. Sólo hay que colocar 1 cucharada de raíz de valeriana triturada y seca en una taza. Luego agrega agua fría o tibia y dejar esta infusión reposar durante la noche. Esta nota es con fines informativos, recuerda consultar con médico si quieres iniciar algún tratamiento con plantas.",
        urlToImage: "https://www.mdzol.com/u/fotografias/m/2021/10/1/f1280x720-1116318_1247993_5050.jpg"
    },
    {
        title: "La oftalmóloga Bárbara Burgos, mejor médica MIR quirúrgica",
        description: "El Colegio de Médicos de Madrid ha otorgado el premio a la mejor médica interno residente a la oftalmóloga Bárbara Burgos. ¿Quieres saber por qué?",
        content: "Una oftalmóloga del Hospital Clínico San Carlos, Bárbara Burgos Blasco, ha sido galardonada con el premio a la mejor médica interno residente (MIR) en el área quirúrgica por el Colegio Oficial de Médicos de Madrid, en los premios 'fin de residencia' de 2021, que destacan la excelencia durante la formación MIR. Bárbara Burgos realizó su residencia en el Servicio de Oftalmología del Clínico San Carlos entre 2017 y 2021, periodo en el que amplió su formación con la realización de varios estudios de postgrado, como el Máster en Ciencias de la Visión por la Universidad Complutense de Madrid y el Máster en Oftalmología Clínica por la Universidad San Pablo CEU. También destaca su papel investigador con más de 60 publicaciones en revistas internacionales, habiendo dirigido múltiples proyectos de investigación del Servicio de Oftalmología del Hospital Clínico. También es revisora científica en varias revistas de alto impacto en la especialidad de oftalmología. Actualmente, Bárbara Burgos desarrolla su actividad profesional en la Unidad de Superficie e Inflamación Ocular del Servicio de Oftalmología del Hospital Clínico San Carlos y en el Banco de Tejidos del hospital. Esta es la segunda ocasión consecutiva en la que un médico residente de Oftalmología del Hospital Clínico San Carlos se hace merecedor de este galardón, lo que incide en la preparación y talento de los jóvenes oftalmólogos de este hospital público madrileño, ya que en 2020 esta distinción recayó en Blanca Benito Pascual, médica residente entre los años 2016 y 2020 en el Clínico y que actualmente se encuentra ampliando su formación y experiencia como especialista realizando un período de capacitación en córnea en el prestigioso Sydney Eye Hospital, en Australia.",
        urlToImage: "https://www.redaccionmedica.com/images/destacados/barbara-burgos-clinico-san-carlos-mejor-mir-de-quirurgica-de-madrid-4299_620x368_mark.jpg"
    },
    {
        title: "Legalización cannabis: Neumología y Psiquiatría la rechazan",
        description: "Especialistas analizan la Proposición de Ley Integral del Cannabis presentada por Más País-Equo y avisan que la marihuana es 'peligrosa' para la salud",
        content: "Más País-Equo ha registrado esta semana la Proposición de Ley Integral del Cannabis. Su objetivo es despenalizar su consumo, además de permitir llevar consigo diez veces la cantidad diaria permitida para fumar. En este escenario, la Sociedad Española de Neumología y Cirugía Torácica (Separ) y la Sociedad Española de Psiquiatría (SEP) coinciden en señalar que el consumo de esta sustancia es perjudicial para la salud, puesto que el cannabis es una droga; y que todo lo que tenga que ver con su legalización no es 'beneficioso'. Carlos A. Jiménez Ruíz, neumólogo y presidente de Separ, en conversación con Redacción Médica afirma que el consumo de esta sustancia es 'perjudicial' para la salud y señala que no tiene conocimiento de cómo se va a llevar a cabo esta ley ni cuál va a ser su base, pero recomienda que antes de dar el siguiente paso, se escuche a la voz de los expertos. 'Hablo sobre el consumo de cannabis en cuanto a la salud respiratoria y tenemos que saber que es peligroso teniendo en cuenta que va asociado a diferentes enfermedades respiratorias como puede ser el cáncer de pulmón', afirma Jiménez Ruíz. En un trabajo en  el que ha participado Separ se hace alusión al daño que puede ocasionar el consumo de marihuana sobre el aparato respiratorio, no solo por las implicaciones sanitarias derivadas de la elevada prevalencia de consumo ilegal, sino porque se propone actualmente su uso medicinal y recreativo en varios países. 'Somos conocedores de que hay especialistas en algunos temas que dicen que el consumo de cannabis de forma reglada, como medicamentos, es bueno para la salud y para controlar ciertas patologías, pero yo hablo sobre el riesgo que tiene este consumo para la salud respiratoria', comenta Jiménez Ruíz.",
        urlToImage: "https://www.redaccionmedica.com/images/destacados/los-medicos-descartan-una-regulacion-del-cannabis-de-la-que-no-sean-parte-3643_620x368.jpg"
    },
    {
        title: "COVID-19: un tercio de los pacientes de Reino Unido tuvo síntomas hasta seis meses después del alta",
        description: "Al menos 1 de cada 3 personas que se infectaron con el coronavirus manifestaron signos de lo que se conoce como COVID prolongado, según un nuevo estudio de la Universidad de Oxford. Cuáles son los síntomas más frecuentes",
        content: "Los alcances de lo que los médicos dieron en llamar COVID prolongado, long COVID o síndrome post COVID se siguen estudiando en el devenir de la pandemia. Se trata ni más ni menos de afectaciones en órganos que van más allá del sistema respiratorio y que son propias del cuadro inflamatorio sistémico que provoca el SARS-CoV-2 en el organismo. Un estudio realizado por investigadores de la Universidad de Oxford y el Instituto Nacional de Investigación en Salud en el Reino Unido mostró que casi cuatro de cada diez personas que se infectaron con el nuevo coronavirus todavía tenían al menos un síntoma entre tres y seis meses después. Según observaron los autores de la investigación, los síntomas persistentes más comunes entre las más de 270.000 personas encuestadas fueron ansiedad y depresión, dificultad para respirar, problemas abdominales, fatiga y dolor muscular. Para el análisis, los investigadores compararon el riesgo de características de COVID prolongado en diferentes grupos dentro de la población y también contrastaron el riesgo con el de la influenza. Los síntomas fueron más frecuentes entre las personas que habían sido hospitalizadas previamente con COVID-19 y fueron un poco más comunes entre las mujeres, según el estudio. Y si bien el estudio no proporcionó ninguna causa detallada de los síntomas de COVID prolongados, su gravedad o cuánto tiempo podrían durar, especificó que las personas mayores y los hombres tenían más dificultades respiratorias y problemas cognitivos, mientras que los jóvenes y las mujeres tenían más dolores de cabeza, síntomas abdominales y ansiedad o depresión. “Conocer el riesgo de las funciones de COVID prolongado ayuda a planificar la prestación de servicios de atención médica relevante”, evaluaron los autores en las conclusiones de su trabajo publicado en la revista Plos Medicine. Para ellos, “el hecho de que el riesgo sea mayor después de COVID-19 que después de la influenza sugiere que su origen podría, en parte, involucrar directamente la infección por SARS-CoV-2 y no es solo una consecuencia general de la infección viral. Esto podría ayudar a desarrollar tratamientos efectivos contra COVID prolongado”.",
        urlToImage: "https://www.infobae.com/new-resizer/HFXavl6apebUhfuM0aQ-5kvSuT4=/1200x628/filters:format(jpg):quality(85)//cloudfront-us-east-1.images.arcpublishing.com/infobae/SIU2PLR3C5FOXJYU6HVOSM3L3A.jpg"
    },
    {
        title: "La salud de Mirtha Legrand: dos personas disfrazadas de médicos intentaron ingresar al sanatorio para sacarle una foto",
        description: "Desde el entorno de la diva confirmaron el episodio a TN Show. El personal de seguridad del Mater Dei les impidió el paso.",
        content: "Después de sufrir un malestar en el pecho este jueves, Mirtha Legrand fue ingresada al Sanatorio Mater Dei, donde le colocaron dos stents y quedó internada para un mayor control. Este viernes sucedió un hecho insólito: desde el entorno de La Chiqui confirmaron a TN Show que dos intrusos intentaron ingresar disfrazados de médicos para tomarle una foto, pero fueron detenidos por la seguridad del hospital. De acuerdo a lo expresado en el último parte médico, la conductora está de buen ánimo y presenta una evolución favorable, aunque continuará en la unidad coronaria. El sábado a las 11 volverán a informar sobre su estado de salud. Sin embargo, ocurrió un episodio insólito. Según informó Pía Shaw en el aire de Los ángeles de la mañana (eltrece) dos hombres disfrazados de médico y enfermero intentaron ingresar al piso donde se encuentra Mirtha para tomarle fotografías. “¿De algún medio o freelance?”, consultó Ángel de Brito. La angelita dijo que no se sabía esa información, pero destacó el rol del personal de seguridad que se dio cuenta y les impidió el paso. Esta misma información fue confirmada por este medio. Desde el entorno de la familia de Mirtha, aseguraron que este episodio ocurrió, pero no dieron mayores detalles.",
        urlToImage: "https://tn.com.ar/resizer/s_zY3PDCwpZQ375pYXcgEFm8eEM=/1023x0/smart/filters:quality(60)/thumbs.vodgc.net/B326945C3F857B7A616E1FC9D37DC7B1134-1633116900.jpg"
    }
]