module.exports = independiente = [
    {
        title: "La jugada de Falcioni para enfrentar a Vélez",
        description: "El técnico probó con línea de cinco, pero finalmente optará por jugar con cuatro en el fondo y sacará a un jugador por bajo rendimiento.",
        content: "El sueño del campeonato pareció comenzar a quedar lejos en Independiente luego de la dura derrota sufrida frente a Godoy Cruz por 4-1. Y no sólo por la distancia que separa al equipo de Avellaneda de la cima de la tabla en la Liga Profesional, sino también por el mal rendimiento que tuvo un equipo que no logra trascender la irregularidad. Julio César Falcioni considera que el último tres aún no pasó. Y cree que el partido de este sábado frente a Vélez, en el estadio José Amalfitani, puede ser determinante para las aspiraciones de sus dirigidos. 'Todo lo malo que nos podía pasar en el último partido, nos pasó. Fueron cosas que vimos, analizamos y hablamos mucho, pero igual no pudimos resolverlo en la cancha. Tenemos que volver a jugar como lo veníamos haciendo, con la seguridad y confianza que tuvimos durante todo el año', comentó el Emperador. El entrenador se la jugará en defensa. Thomas Ortega, quien viene de convertir un gol en contra y se mostró muy flojo en la marca en el último encuentro, será reemplazado por Ayrton Costa, zaguero de 22 años que lleva disputados 901 minutos en Independiente repartidos en 13 partidos, 11 de ellos de titular. Brian Martínez, quien en la práctica del jueves fue reemplazado por Joaquín Laso, permanecerá en el equipo y el esquema será un 4-3-2-1. 'Nos vamos a levantar como lo venimos haciendo siempre. Sabemos que no podemos dejar escapar más puntos, no podemos perder. La última derrota nos dolió, pero este equipo ya dio muestras de carácter y tenemos que volver a hacer lo mismo', expresó Sebastián Sosa.",
        urlToImage: "https://images.ole.com.ar/2021/10/01/rW-ciGRNA_1256x620__1.jpg"
    },
    {
        title: "De terror: la barra de Independiente se enfrentó a los tiros en el centro de Avellaneda",
        description: "Dos facciones empezaron la pelea en la puerta de la sede y continuaron en la calle. Hubo 19 detenidos. ¡Y se secuestraron dos autos de lujo!",
        content: "Tiros, corridas, peleas. Locura total. Dos facciones de la barra brava de Independiente se enfrentaron este martes por la tarde en pleno centro de Avellaneda. Empezaron en la sede del club de la Avenida Mitre, pero el choque llegó hasta la Avenida Belgrano. Hubo heridos y, de acuerdo a la información policial,19 barras fueron detenidos cuando intentaban ingresar a la Capital Federal por el Puente Pueyrredon Viejo. Los violentos fueron trasladados a la Comisaría primera de Avellaneda. Uno de los detenidos es el líder de la facción disidente, César Loquillo Rodríguez. También se secuestraron dos autos alta gama: un BMW y un Mercedes Benz. Y una pistola 9 milímetros Taurus con siete cartuchos. La interna se reaviva justo en la semana previa al regreso del público a las canchas, mientras los clubes empiezan a empadronar a sus socios. La gente que caminaba por las calles, los vecinos y las personas que circulaban en autos y transporte público se encontraron con esa balacera feroz. Una de las peleas se dio justo en la puerta de un colegio. Los videos que circulan en las redes sociales dan cuenta de la locura que generaron los violentos. En una de las imágenes se ve lo que ocurrió en la intersección de Mitre y España, a unos 50 metros de la sede del club. En las segundas, las corridas que hubo en Belgrano y España.",
        urlToImage: "https://images.ole.com.ar/2021/09/28/zRUQM6SLM_1256x620__1.jpg"
    },
    {
        title: "Falcioni bancó a Romero: “Va a revertir la mala racha”",
        description: "El técnico de Independiente salió a respaldar al delantero y capitán de Independiente, quien lleva siete partidos de sequía.",
        content: "Pasaron 47 días desde la última vez que Silvio Romero gritó un gol propio. El delantero de 33 años lleva siete partidos sin convertir. Sus últimos gritos fueron el 14 de agosto, cuando convirtió un doblete frente a Rosario Central (2-1) en el Gigante de Arroyito. Después de ese encuentro, el delantero no pudo convertir contra Defensa y Justicia (0-0), Atlético Tucumán (2-0), Colón (3-0), River (1-1), Lanús (0-1), Huracán (1-0) y Godoy Cruz (1-4). No sólo él padece la sequía, sino que también el equipo: hasta antes de la mala racha, el Chino había anotado cuatro goles en los primeros seis partidos del Rojo en la Liga Profesional. Y su comienzo del semestre había sido muy bueno, ya que el 9 de agosto metió el gol del triunfo contra Racing (1-0) y también había anotado ante Tigre (1-2), por Copa Argentina. El goleador venía encendido, pero en los últimos encuentros no tuvo participación en el juego. Salvo en el duelo frente a Colón, en el que tuvo pocas pero buenas intervenciones, en el resto de los partidos entró muy poco en contacto con la pelota: fue el jugador que menos la tocó en tres de los siete partidos de su sequía y el segundo con menos participación en los otros cuatro. En ese contexto, Julio Falcioni aprovechó la conferencia de prensa de este jueves para darle un fuerte respaldo. 'Silvio es nuestro referente y capitán. Hizo el gol más importante del campeonato. Confío en que va a revertir la mala racha', comentó el entrenador de 65 años. Y agregó: 'Los goleadores siempre son así. A veces están de racha y a veces no. Es un jugador que en cualquier momento te puede ganar un partido'. Para el entrenador, Romero es titular indiscutido a pesar de que atraviesa uno de los peores momentos desde que llegó al club a principios de 2018. Además, no son muchas las variantes que tiene en el puesto: Jonathan Herrera se recuperó de un cuadro de anemia y también cuenta con los juveniles Julián Romero y Ángel Sayago. En ese contexto, el Emperador mantendrá su apuesta por el Chino.",
        urlToImage: "https://images.ole.com.ar/2021/09/30/y7KA6X3Tj_1256x620__1.jpg"
    },
    {
        title: "El repudio de Independiente tras la batalla",
        description: "El club aseguró que la pelea está en contra de lo que quiere la entidad y si hay socios involucrados les impedirá el ingreso a la cancha.",
        content: "Este martes hubo un fuerte enfrentamiento entre dos sectores de la barra brava de Independiente. Fue de terror: corridas y tiros en el centro de Avellaneda. El club sacó un comunicado de repudió tras los incidentes y anunció que, de haber socios involucrados, estos no podrán ingresar a la cancha para los partidos de local. 'El Club Atlético Independiente repudia terminantemente los hechos de violencia ocurridos esta tarde en el centro de nuestra querida Avellaneda. El accionar de estos grupos representa todo lo que no queremos para nuestra institución y sociedad en general. En este momento tan especial, en vísperas del regreso del público a los estadios, queremos llevar tranquilidad a todos nuestros hinchas y asociados. Continuaremos trabajando para que todos disfrutemos en paz cada encuentro disputado en el Libertadores de América y cada actividad que suceda en nuestras instalaciones.' Durante la batalla, hubo heridos y, según la policía,19 barras fueron detenidos cuando intentaban ingresar a la Capital Federal por el Puente Pueyrredon Viejo. Uno de los aprehendidos es el líder de la facción disidente, César Loquillo Rodríguez.",
        urlToImage: "https://images.ole.com.ar/2021/09/28/Uq8edbPGO_1256x620__2.jpg#1632873594304"
    }
]