module.exports = racing = [
    {
        title: "Cvitanich: “Si tengo que quedarme de alcanzapelotas, me quedo...”",
        description: "El atacante usó esa exageración para expresar su deseo de seguir en Racing, post diciembre, si se siente bien.",
        content: "Había sido categórico Darío Cvitanich después de la derrota ante Argentinos Juniors. 'Es un ciclo terminado, hay que dar un paso al costado', dijo, tajante, el delantero de 37 años que posee contrato hasta fin de este año. Sin embargo, ya sin la calentura con que se expresó en ese momento, el atacante recuperó el discurso mesurado que lo caracteriza y dio una marcha atrás. A horas del cruce con Estudiantes (domingo a las 20.15), que marcará el regreso del público al Cilindro, Cvita dejó una puerta abierta para renovar vínculo con la Academia. 'El otro día, después del partido, me fui muy mal a mi casa. Pero hoy digo que quiero seguir jugando y hacerlo cada vez mejor, más allá de la edad. Uno siempre quiere jugar, pero si me tengo que quedar de alcanzapelotas, me quedo . Lo que más quiero es entrar a disfrutar', declaró en charla con TyC Sports. Darío será suplente frente al elenco de Ricardo Zielinski. Él ex Banfield ya renovó dos veces su convenio con la Academia. El 31 de diciembre caducará el actual y seguramente se sentará a hablar con los dirigentes para definir su futuro: 'Tendremos que ver cómo seguiremos. Si continúo en el club es porque creo que puedo aportar algo. Hoy es un tema que no me planteo, vivo día a día'. Y se refirió a la situación difícil que atraviesa el equipo, siempre con su postura de focalizar más en el juego que en los resultados. 'Las sensaciones que uno tiene -aclaró- van más allá de un momento malo. Hace unos meses nos tocó jugar una final (derrota por 3-0 ante Colón), pero yo no estaba conforme con el nivel del equipo. Si la hubiéramos ganado, tampoco habría cambiado de parecer'",
        urlToImage: "https://images.ole.com.ar/2021/10/02/ns_VnBGvR_1256x620__2.jpg#1633197308881"
    },
    {
        title: "Formación definida de Racing para recibir a Estudiantes",
        description: "En las tareas de pelota parada, Úbeda repitió los seis cambios para enfrentar al Pincha. Regresa Licha López.",
        content: "No hubo sorpresas en los ejercicios de pelota parada. Allí, Claudio Úbeda repitió a los mimos 11 que había colocado en el ensayo de fútbol formal y el técnico de Racing ya tiene todo definido. Seis, entonces, serán los cambios que incluirá para recibir este domingo, desde las 20.15, a Estudiantes en un día muy especial: el público regresará al Cilindro después de la pandemia de Covid-19. No se queda quieto el Sifón. Insiste, persevera, ajusta, mueve piezas. Desde que llegó a Racing como reemplazante de Juan Antonio Pizzi hasta diciembre, el técnico ha realizado variantes de nombres y de esquema en busca de elevar el flojo funcionamiento que llevó a equipo a una racha de siete juegos sin triunfos. Entre las variantes se destacan los retornos de Lisandro López y Nery Domínguez, más el debut como titular de Gastón Viera, extremo de 19 años. Además, habrá otro dibujo táctico: el DT dejará el 4-1-3-2 que venía empleando desde el clásico con San Lorenzo y volverá a un 4-2-3-1 que, por momentos, mutará ene un 4-1-4-1. Licha fue el banco en la derrota ante Argentinos, pero no entró porque no estaba al ciento por ciento por una sobrecarga muscular y se había pactado con el cuerpo técnico que no jugara para evitar riesgos de lesión. Úbeda lo concentró y sentó a su lado por lo que significa su presencia en el grupo. Ya recuperado, el capitán va irá por Ignacio Piatti. Nery, a su vez, ni siquiera fue citado para el último encuentro a raíz de una sobrecarga en el gemelo izquierdo. Y no sólo que reaparecerá, sino que retornará a su puesto original de volante, posición que cumplió por última vez justamente contra el Pincha, en febrero pasado, en un 0-0. El movimiento de Nery generó otro en la zaga. Joaquín Novillo ingresará por Mauricio Martínez, de error grosero en el primero de los dos goles de Argentinos en la derrota por 2-0. En definitiva, según los últimos entrenamientos, la Academia alineará a Gabriel Arias; Juan Cáceres, Leonardo Sigali, Joaquín Novillo, Fernando Prado; Nery Domínguez, Aníbal Moreno; Gastón Viera, Licha López, Carlos Alcaraz; Enzo Copetti.",
        urlToImage: "https://images.ole.com.ar/2021/10/02/Xj-VgKez6_1256x620__2.jpg#1633194738679"
    },
    {
        title: "Arias: “La gente nos va a apoyar más que nunca”",
        description: "El arquero de Racing imagina que los hinchas alentarán mucho en la vuelta al Cilindro pese al mal año del equipo.",
        content: "La cabeza de Gabriel Arias se reparte en varios focos. El deseo ferviente de volver al triunfo después de siete partidos, recuperar la valla en cero que perdió hace tres juegos y, por sobre todas las cosas, poder disfrutar del regreso del público al Cilindro luego de 20 meses. Al arquero, uno de los mejores en su puesto en el fútbol argentino, le hubiera gustado llegar a este reencuentro con los hinchas en un equipo en una mejor forma futbolística. Es consciente de que la gente acumuló frustración sin poder expresarla más allá de las redes sociales, pero está convencido de que va a primar el respaldo. 'No me quedan dudas de que la gente va a venir a alentar. Lo he vivido desde que estoy acá, lo vi cuando lo enfrenté a Racing. Pueden estar en disconformidad con los dirigentes o lo que sea, pero no nos van a dejar solos. Nos van a apoyar más que nunca. Eso lo vamos a sentir y nos vendrá muy bien', aseguró el neuquino nacionalizado chileno, ya un referente del plantel que ha usado la cinta de capitán en varias ocasiones cuando faltó Licha López.",
        urlToImage: "https://images.ole.com.ar/2021/08/28/Mr9rS8X-B_1256x620__3.jpg#1633123746807"
    },
    {
        title: "Cumbre en Racing: Blanco habló con los jugadores",
        description: "El presidente mantuvo una reunión con los referentes y pidió más compromiso. Y a Úbeda le dio tranquilidad para seguir.",
        content: "Fue una mañana de miércoles a pura reunión. Terminado el entrenamiento matutino en Avellaneda, tanto el cuerpo técnico como los máximos referentes del plantel tuvieron charlas por separado con la cúpula directiva de Racing. El presidente Víctor Blanco y Miguel Jiménez (vice segundo y hombre con peso en las decisiones futbolísticas) se hicieron presentes para dejar en claro algunas cuestiones que parecían haberse ido de las manos en los últimos días. En primer lugar, al Sifón le llevaron tranquilidad y le dieron respaldo luego de que empezaran a sonar con fuerza algunos técnicos. Se habló de Guillermo Barros Schelotto y de Gabriel Heinze, pero ninguno llegará. No al menos hasta terminado el año. Los Mellizos todavía están vinculados a Los Angeles Galaxy, equipo al que ya no dirigen. En su salida arreglaron que no pueden trabajar ni en la MLS ni en Argentina. Se bajaron al igual que Heinze. Hace un mes, Blanco se comunicó con el ex DT de Vélez, que agradeció pero avisó que no está interesado en volver al país. Lo dijo desde España. La realidad es que ningún DT que gusta en Racing está en condiciones de arribar en estos momentos. El Cacique Medina y Javier Mascherano son otros en consideración, pero recién para enero. Por eso la intención de la dirigencia es darle continuidad al golpeado proceso de Úbeda. Sabe que los resultados mandan y la Academia hace siete partidos que no gana, pero no ve una salida sin el Sifón y por eso lo va a mantener todo lo que pueda. Para eso es vital un triunfo el domingo contra Estudiantes, en la vuelta de los hinchas. Además de hablar con Úbeda, los dirigentes también charlaron con los referentes del plantel. Lisandro López, Darío Cvitanich, Gabriel Arias, Leonardo Sigali y Nery Domínguez fueron los que tuvieron el cara a cara. Es sabido que el actual DT tiene la banca de ellos. Lo que se habló no fue en torno al Sifón, sino al plantel. Hubo un pedido para que los líderes del grupo bajen un mensaje de mayor compromiso al resto, ya que notan que algunos jugadores no lo tienen como en el pasado. En las últimas semanas hubo varias actitudes que no gustaron en la dirigencia y quieren que algunos jugadores (que no son los referentes) adopten otra conducta, más acorde al momento que vive el equipo y que tiren todos para el mismo lado. En definitiva, creen que el mal presente del equipo no es responsabilidad principal del entrenador y por eso no están convencidos de contratar a otro DT que no tenga la aprobación unánime de la dirigencia. Son tiempos turbulentos, de los que hace mucho tiempo no había en Racing.",
        urlToImage: "https://images.ole.com.ar/2021/09/29/VP2MSGta8_1256x620__1.jpg"
    }
]