module.exports = river = [
    {
        title: "El plantel de River y una Súper despedida bajo la lluvia",
        description: "El equipo de Gallardo se entrenó en el Monumental antes del superclásico y tuvo un aliento especial.",
        content: "La ansiedad aumenta minuto a minuto y no hay lluvia que pueda apagar la pasión de los hinchas de River en la previa del superclásico. A pesar de que este sábado al mediodía el clima en la Ciudad de Buenos Aires no acompañó, algunos fanáticos fueron a despedir al plantel de Marcelo Gallardo a la salida del Monumental, lugar elegido para llevar adelante la última práctica antes del choque de este domingo. En la antesala de lo que será la ansiada vuelta del público a Núñez después de 582 días, los hinchas que estaban en el club haciendo deportes vieron el micro, agarraron las camperas y los pilotos para protegerse del agua y se acercaron a observar de cerca a sus ídolos. Con mucha buena, uno a uno los jugadores fueron agradeciendo las muestras de cariño y, como no podía ser de otra manera, el Muñeco se llevó una de las mayores ovaciones. MG organizó la práctica en el Monumental por segunda vez en la semana para tratar de sacarle el máximo provecho al césped y a la vez dejar las dudas que tiene, sobre todo en la mitad de la cancha. A diferencia del jueves, esta vez el deté no paró un equipo, pero hizo algunos trabajos tácticos para ajustar detalles y tratar de sacar las últimas conclusiones. Sin David Martínez, la defensa sale de memoria: Franco Armani, Milton Casco, Robert Rojas, Paulo Díaz y Fabrizio Angileri. Mientras tanto, Enzo Pérez, Nicolás de la Cruz y Jorge Carrascal asoman como fijas en un mediocampo en el que Enzo Fernández, Santiago Simón, Bruno Zuculini y Agustín Palavecino pelean por ganarse la última vacante.",
        urlToImage: "https://images.ole.com.ar/2021/10/02/PtNLnLk1v_1256x620__2.jpg#1633204858182",
        id: '3320485818'
    },
    {
        title: "El ex Boca y River que no dudó: “Fui más feliz en...”",
        description: "Bruno Urribarri palpitó el superclásico y se la jugó a la hora de elegir a su candidato para el choque de este domingo.",
        content: "A sus 34 años, Bruno Urribarri es uno de los integrantes de la exclusiva lista de jugadores que se dieron el gusto de ponerse las camisetas de River y de Boca. Las fotos en las que luce los colores de los clubes más grandes del fútbol argentino son recuerdos imborrables y el superclásico siempre es un partido especial para él. Sin embargo, a la hora de elegir a su favorito para el choque de este domingo en el Monumental, fue contundente. Lejos de despejar la pelota al lateral, mostró la misma convicción con la que pasa al ataque. 'Sin dudas, voy a hinchar por River, por mi infancia con los CDs de Ignacio Copani sonando', expresó el lateral izquierdo de Patronato, que se fue del Xeneize en 2007 (jugó apenas 10 partidos) y llegó al club de Núñez en enero de 2014 tras sus pasos por Argentinos, Asteras Tripolis (Grecia) y Colón. 'No tenía noción de dónde estaba. Esa adrenalina, ese miedo, esa responsabilidad hacía que no tome dimensión. Y también la edad.. No valoré tanto ese tiempo en Boca y con el correr de los años me di cuenta que estuve en un lugar privilegiado. Por todo eso, fui más feliz en River. Me agarró en otro momento de mi vida, me sentí muy a gusto con el grupo y viví un año y medio hermoso. Me fui porque no demostré tener el nivel para lo que necesitaba el equipo en ese momento', agregó.",
        urlToImage: "https://images.ole.com.ar/2021/10/02/P9MbtpQB0_1256x620__1.jpg",
        id: 'P9MbtpQBa'
    },
    {
        title: "El Monumental que se encontrarán los hinchas de River",
        description: "Los más de 36 mil fanas que asistirán al superclásico van a disfrutar de un estadio totalmente renovado.",
        content: "La espera fue extensa, difícil de llevar adelante, pero finalmente llegó la ansiada hora de volver a casa y el reencuentro será más que especial. Después de 582 días del último partido de River como local con el aliento de su gente (29/2/20 ante Defensa), los más de 36 mil hinchas que tengan la suerte de presenciar el superclásico se van a encontrar con un Monumental totalmente renovado. Si bien la alfombra verde de primer nivel que enamoró a Marcelo Gallardo y hasta a Lionel Scaloni se roba todas las miradas, los fanas podrán disfrutar de otras importantes mejoras que van desde lo edilicio hasta lo tecnológico. La inversión de casi 200 millones de pesos que hizo el club de Núñez para completar una obra que se llevó a cabo durante siete meses generó un cambio radical en la cancha. La instalación del nuevo césped híbrido (95% natural y un 5% sintético) es la joyita. Se debió bajar 180 centímetros el nivel del suelo -se excavaron y retiraron 35.000 m3 de tierra- y se demolieron 1325 m3 de hormigón armado de la pista de atletismo y túneles de salida de los vestuarios local, visitante y árbitros, trabajos que en un futuro permitirán subir la capacidad de 72.054 espectadores a cerca de 80.000. El terreno de juego, que posee un nuevo sistema de drenaje y control de temperatura subterránea para que luzca en perfectas condiciones durante todo el año, no fue lo único que le cambió la fisonomía al Monumental. La nueva iluminación 100% LED permite una mejor visibilidad los partidos nocturnos y las tribunas lucen distintas. La remoción de un antiguo muro que quedó en las troneras del estadio permitió incrementar el número de plateas, se mejoró la circulación entre las tribunas bajas y medias, y en la Belgrano media se facilitó la accesibilidad para las personas con movilidad reducida. Los baños también forman parte de este cambio de look del Vespucio Liberti. Se reformaron a nuevo en todas las tribunas con nuevos pisos, cerámicos y grifería de última generación, mientras que en la San Martín baja/media se agregó uno de damas. A su vez, se construyeron los nuevos puestos gastronómicos en tribunas bajas, que en total ocupan una superficie de 770 metros cuadrados. ¡Cómo se extrañaba la hamburguesa de cancha!",
        urlToImage: "https://images.ole.com.ar/2021/03/16/ipsnR1ZIL_1256x620__3.jpg#1632778771374",
        id: '6327787713Vm'
    },
    {
        title: "El 11 de River vs. Boca y las incógnitas de Gallardo",
        description: "El Muñeco define algunas cuestiones en el medio y en la ofensiva. ¿Quién será el socio de Julián Alvarez?",
        content: "Analiza opciones, revisa nombres, mueve piezas, juega al despiste... El River-Boca está cada vez más cerca, pero Marcelo Gallardo, como buen estratega que es, se toma su tiempo para definir el equipo. 'El día que jugué el superclásico me enteré en la charla, media hora antes de salir al estadio', reconoció Lucas Beltrán (hoy en Colón), sorpresivo titular en el primer superclásico de 2021. Sin embargo, tal como lo reflejó en la conferencia de prensa, el DT tiene muchas certezas y dos incógnitas puntuales. Sin David Martínez ('Es imposible que esté el domingo', había adelantado MG), el equipo perderá a una pieza fundamental en el fondo y la defensa sale de memoria: Franco Armani, Milton Casco, Robert Rojas, Paulo Díaz y Fabrizio Angileri. A su vez, Javier Pinola, la gran sorpresa de la lista, será alternativa luego de haberse rehabilitado de una fractura de cúbito derecho. Enzo Pérez, Nicolás de la Cruz y Jorge Carrascal asoman como fijas en un mediocampo con varios nombres para un sólo lugar. En la práctica de este jueves en Monumental, Gallardo probó con Enzo Fernández, pero Santiago Simón, Agustín Palavecino y Bruno Zuculini también pelean por esa plaza entre los titulares. A su vez, con respecto al 10 colombiano, el entrenador volvió a remarcar que necesita que tenga 'continuidad en su talento'. Arriba, el dilema pasa por saber quién acompañará a Julián Alvarez, la principal carta goleadora del equipo en lo que va del 2021 (11 gritos y 13 pases gol). Las principales opciones son Braian Romero, goleador con experiencia y acostumbrado al roce teniendo en cuenta un posible duelo con la zaga Rojo-Izquierdoz, o el juvenil Benjamín Rollheiser, un punta más veloz y que jugó de entrada en las dos últimas fechas, ante Arsenal y Central Córdoba de Santiago. Detrás, según las palabras del DT, parece difícil que Matías Suárez ingrese de entrada. 'Es un jugador de muchísima jerarquía que ha venido sufriendo físicamente y no pudo estar a disposición en este último tiempo. Veremos a ver si llega un poco mejor para ver si puede jugar algún tiempo', expresó MG acerca del estado físico del cordobés, quien este viernes estuvo viendo a la Reserva con hielo en su rodilla derecha, la misma que lo tiene a maltraer por culpa de una sinovitis. Pasando en limpio, el probable 11 de River para jugar ante domingo ante Boca en un Monumental con más de 36 mil personas sería: Franco Armani; Milton Casco, Robert Rojas, Paulo Díaz, Fabrizio Angileri; Fernández / Palavecino / Zuculini, Enzo Pérez, De la Cruz; Jorge Carrascal; Romero / Rollheiser / Suárez y Julián Alvarez.",
        urlToImage: "https://images.ole.com.ar/2020/12/29/mkC8qXuIo_1256x620__2.jpg#1633184542165",
        id: '3318454216mL'
    }
]