module.exports = teams = [
    {
        team: 'Aldosivi',
        shield: "/assets/img/futbol-icons/teams/aldosivi.png",
        pts: '20',
        pj:'18',
        pg: '6',
        pe: '2',
        pp: '10',
        gf: '19',
        gc: '30',
        dif: '-11'
    },
    {
        team: 'Argentinos',
        shield: "/assets/img/futbol-icons/teams/argentinos.png",
        pts: '24',
        pj:'18',
        pg: '6',
        pe: '6',
        pp: '6',
        gf: '18',
        gc: '18',
        dif: '0'
    },
    {
        team: 'Arsenal',
        shield: "/assets/img/futbol-icons/teams/arsenal.png",
        pts: '13',
        pj:'18',
        pg: '2',
        pe: '7',
        pp: '9',
        gf: '7',
        gc: '23',
        dif: '-16'
    },
    {
        team: 'Atl. Tucuman',
        shield: "/assets/img/futbol-icons/teams/tucuman.png",
        pts: '21',
        pj:'18',
        pg: '5',
        pe: '6',
        pp: '7',
        gf: '19',
        gc: '26',
        dif: '-7'
    },
    {
        team: 'Banfield',
        shield: "/assets/img/futbol-icons/teams/banfield.png",
        pts: '15',
        pj:'18',
        pg: '2',
        pe: '9',
        pp: '7',
        gf: '13',
        gc: '21',
        dif: '-8'
    },
    {
        team: 'Boca',
        shield: "/assets/img/futbol-icons/teams/boca.png",
        pts: '30',
        pj:'18',
        pg: '8',
        pe: '6',
        pp: '4',
        gf: '21',
        gc: '15',
        dif: '+6'
    },
    {
        team: 'Central Cba',
        shield: "/assets/img/futbol-icons/teams/centralcordoba.png",
        pts: '13',
        pj:'18',
        pg: '2',
        pe: '7',
        pp: '9',
        gf: '18',
        gc: '26',
        dif: '-8'
    },
    {
        team: 'Colon',
        shield: "/assets/img/futbol-icons/teams/colon.png",
        pts: '29',
        pj:'18',
        pg: '8',
        pe: '5',
        pp: '5',
        gf: '16',
        gc: '20',
        dif: '-4'
    },
    {
        team: 'Def. y Justicia',
        shield: "/assets/img/futbol-icons/teams/defensa.png",
        pts: '28',
        pj:'18',
        pg: '7',
        pe: '7',
        pp: '4',
        gf: '25',
        gc: '17',
        dif: '+8'
    },
    {
        team: 'Estudiantes',
        shield: "/assets/img/futbol-icons/teams/estudiantes.png",
        pts: '27',
        pj:'18',
        pg: '7',
        pe: '6',
        pp: '5',
        gf: '27',
        gc: '20',
        dif: '+7'
    },
    {
        team: 'Gimnasia',
        shield: "/assets/img/futbol-icons/teams/gimnasia.png",
        pts: '25',
        pj:'18',
        pg: '6',
        pe: '7',
        pp: '5',
        gf: '16',
        gc: '18',
        dif: '-2'
    },
    {
        team: 'Godoy Cruz',
        shield: "/assets/img/futbol-icons/teams/godoycruz.png",
        pts: '26',
        pj:'18',
        pg: '7',
        pe: '5',
        pp: '6',
        gf: '28',
        gc: '23',
        dif: '+5'
    },
    {
        team: 'Huracan',
        shield: "/assets/img/futbol-icons/teams/huracan.png",
        pts: '28',
        pj:'18',
        pg: '7',
        pe: '7',
        pp: '4',
        gf: '18',
        gc: '14',
        dif: '+4'
    },
    {
        team: 'Independiente',
        shield: "/assets/img/futbol-icons/teams/independiente.png",
        pts: '28',
        pj:'18',
        pg: '7',
        pe: '7',
        pp: '4',
        gf: '19',
        gc: '16',
        dif: '+3'
    },
    {
        team: 'Lanus',
        shield: "/assets/img/futbol-icons/teams/lanus.png",
        pts: '31',
        pj:'18',
        pg: '9',
        pe: '4',
        pp: '5',
        gf: '33',
        gc: '29',
        dif: '+4'
    },
    {
        team: 'Newells',
        shield: "/assets/img/futbol-icons/teams/newells.png",
        pts: '17',
        pj:'18',
        pg: '4',
        pe: '5',
        pp: '9',
        gf: '18',
        gc: '26',
        dif: '-8'
    },
    {
        team: 'Patronato',
        shield: "/assets/img/futbol-icons/teams/patronato.png",
        pts: '17',
        pj:'18',
        pg: '3',
        pe: '8',
        pp: '7',
        gf: '18',
        gc: '24',
        dif: '-6'
    },
    {
        team: 'Platense',
        shield: "/assets/img/futbol-icons/teams/platense.png",
        pts: '20',
        pj:'18',
        pg: '4',
        pe: '8',
        pp: '6',
        gf: '20',
        gc: '22',
        dif: '-2'
    },
    {
        team: 'Racing',
        shield: "/assets/img/futbol-icons/teams/racing.png",
        pts: '23',
        pj:'18',
        pg: '5',
        pe: '8',
        pp: '5',
        gf: '15',
        gc: '12',
        dif: '+3'
    },
    {
        team: 'River',
        shield: "/assets/img/futbol-icons/teams/river.png",
        pts: '42',
        pj:'18',
        pg: '13',
        pe: '3',
        pp: '2',
        gf: '37',
        gc: '12',
        dif: '+25'
    },
    {
        team: 'Rosario Central',
        shield: "/assets/img/futbol-icons/teams/central.png",
        pts: '24',
        pj:'18',
        pg: '7',
        pe: '3',
        pp: '8',
        gf: '26',
        gc: '25',
        dif: '+1'
    },
    {
        team: 'San Lorenzo',
        shield: "/assets/img/futbol-icons/teams/sanlorenzo.png",
        pts: '17',
        pj:'18',
        pg: '4',
        pe: '5',
        pp: '9',
        gf: '16',
        gc: '25',
        dif: '-9'
    },
    {
        team: 'Sarmiento',
        shield: "/assets/img/futbol-icons/teams/sarmiento.png",
        pts: '23',
        pj:'18',
        pg: '6',
        pe: '5',
        pp: '7',
        gf: '21',
        gc: '22',
        dif: '-1'
    },
    {
        team: 'Talleres',
        shield: "/assets/img/futbol-icons/teams/talleres.png",
        pts: '33',
        pj:'18',
        pg: '10',
        pe: '3',
        pp: '5',
        gf: '27',
        gc: '19',
        dif: '+8'
    },
    {
        team: 'Union',
        shield: "/assets/img/futbol-icons/teams/union.png",
        pts: '22',
        pj:'18',
        pg: '6',
        pe: '4',
        pp: '8',
        gf: '20',
        gc: '25',
        dif: '-5'
    },
    {
        team: 'Velez',
        shield: "/assets/img/futbol-icons/teams/velez.png",
        pts: '31',
        pj:'18',
        pg: '8',
        pe: '7',
        pp: '3',
        gf: '26',
        gc: '13',
        dif: '+13'
    }
];