module.exports = teams = [
    {
        team: 'Aldosivi',
        shield: "/assets/img/futbol-icons/teams/aldosivi.png",
        pts: '13',
        pj:'13',
        pg: '4',
        pe: '1',
        pp: '8',
        gf: '15',
        gc: '24',
        dif: '-9'
    },
    {
        team: 'Argentinos',
        shield: "/assets/img/futbol-icons/teams/argentinos.png",
        pts: '18',
        pj:'13',
        pg: '4',
        pe: '6',
        pp: '3',
        gf: '11',
        gc: '8',
        dif: '+3'
    },
    {
        team: 'Arsenal',
        shield: "/assets/img/futbol-icons/teams/arsenal.png",
        pts: '11',
        pj:'13',
        pg: '2',
        pe: '5',
        pp: '6',
        gf: '6',
        gc: '19',
        dif: '-13'
    },
    {
        team: 'Atl. Tucuman',
        shield: "/assets/img/futbol-icons/teams/tucuman.png",
        pts: '15',
        pj:'13',
        pg: '4',
        pe: '3',
        pp: '6',
        gf: '12',
        gc: '18',
        dif: '-6'
    },
    {
        team: 'Banfield',
        shield: "/assets/img/futbol-icons/teams/banfield.png",
        pts: '13',
        pj:'13',
        pg: '2',
        pe: '7',
        pp: '4',
        gf: '10',
        gc: '13',
        dif: '-3'
    },
    {
        team: 'Boca',
        shield: "/assets/img/futbol-icons/teams/boca.png",
        pts: '21',
        pj:'13',
        pg: '5',
        pe: '6',
        pp: '2',
        gf: '11',
        gc: '8',
        dif: '+3'
    },
    {
        team: 'Central Cba',
        shield: "/assets/img/futbol-icons/teams/centralcordoba.png",
        pts: '11',
        pj:'13',
        pg: '2',
        pe: '5',
        pp: '6',
        gf: '13',
        gc: '18',
        dif: '-5'
    },
    {
        team: 'Colon',
        shield: "/assets/img/futbol-icons/teams/colon.png",
        pts: '19',
        pj:'13',
        pg: '5',
        pe: '4',
        pp: '4',
        gf: '10',
        gc: '15',
        dif: '-5'
    },
    {
        team: 'Def. y Justicia',
        shield: "/assets/img/futbol-icons/teams/defensa.png",
        pts: '15',
        pj:'13',
        pg: '3',
        pe: '6',
        pp: '4',
        gf: '13',
        gc: '12',
        dif: '+1'
    },
    {
        team: 'Estudiantes',
        shield: "/assets/img/futbol-icons/teams/estudiantes.png",
        pts: '24',
        pj:'13',
        pg: '7',
        pe: '3',
        pp: '3',
        gf: '21',
        gc: '12',
        dif: '+9'
    },
    {
        team: 'Gimnasia',
        shield: "/assets/img/futbol-icons/teams/gimnasia.png",
        pts: '17',
        pj:'13',
        pg: '4',
        pe: '5',
        pp: '4',
        gf: '11',
        gc: '14',
        dif: '-3'
    },
    {
        team: 'Godoy Cruz',
        shield: "/assets/img/futbol-icons/teams/godoycruz.png",
        pts: '20',
        pj:'13',
        pg: '6',
        pe: '2',
        pp: '5',
        gf: '23',
        gc: '18',
        dif: '+5'
    },
    {
        team: 'Huracan',
        shield: "/assets/img/futbol-icons/teams/huracan.png",
        pts: '16',
        pj:'13',
        pg: '3',
        pe: '7',
        pp: '3',
        gf: '9',
        gc: '8',
        dif: '+1'
    },
    {
        team: 'Independiente',
        shield: "/assets/img/futbol-icons/teams/independiente.png",
        pts: '22',
        pj:'13',
        pg: '6',
        pe: '4',
        pp: '3',
        gf: '13',
        gc: '10',
        dif: '+3'
    },
    {
        team: 'Lanus',
        shield: "/assets/img/futbol-icons/teams/lanus.png",
        pts: '23',
        pj:'13',
        pg: '7',
        pe: '2',
        pp: '4',
        gf: '22',
        gc: '19',
        dif: '+3'
    },
    {
        team: 'Newells',
        shield: "/assets/img/futbol-icons/teams/newells.png",
        pts: '15',
        pj:'13',
        pg: '4',
        pe: '3',
        pp: '6',
        gf: '14',
        gc: '19',
        dif: '-5'
    },
    {
        team: 'Patronato',
        shield: "/assets/img/futbol-icons/teams/patronato.png",
        pts: '14',
        pj:'13',
        pg: '3',
        pe: '5',
        pp: '5',
        gf: '10',
        gc: '14',
        dif: '-4'
    },
    {
        team: 'Platense',
        shield: "/assets/img/futbol-icons/teams/platense.png",
        pts: '12',
        pj:'13',
        pg: '2',
        pe: '6',
        pp: '5',
        gf: '15',
        gc: '18',
        dif: '-3'
    },
    {
        team: 'Racing',
        shield: "/assets/img/futbol-icons/teams/racing.png",
        pts: '18',
        pj:'13',
        pg: '4',
        pe: '6',
        pp: '3',
        gf: '10',
        gc: '6',
        dif: '+4'
    },
    {
        team: 'River',
        shield: "/assets/img/futbol-icons/teams/river.png",
        pts: '27',
        pj:'13',
        pg: '8',
        pe: '3',
        pp: '2',
        gf: '26',
        gc: '10',
        dif: '+16'
    },
    {
        team: 'Rosario Central',
        shield: "/assets/img/futbol-icons/teams/central.png",
        pts: '16',
        pj:'13',
        pg: '5',
        pe: '1',
        pp: '7',
        gf: '18',
        gc: '18',
        dif: '0'
    },
    {
        team: 'San Lorenzo',
        shield: "/assets/img/futbol-icons/teams/sanlorenzo.png",
        pts: '16',
        pj:'13',
        pg: '4',
        pe: '4',
        pp: '5',
        gf: '12',
        gc: '15',
        dif: '-3'
    },
    {
        team: 'Sarmiento',
        shield: "/assets/img/futbol-icons/teams/sarmiento.png",
        pts: '13',
        pj:'13',
        pg: '3',
        pe: '4',
        pp: '6',
        gf: '11',
        gc: '16',
        dif: '-5'
    },
    {
        team: 'Talleres',
        shield: "/assets/img/futbol-icons/teams/talleres.png",
        pts: '29',
        pj:'13',
        pg: '9',
        pe: '2',
        pp: '2',
        gf: '22',
        gc: '10',
        dif: '+12'
    },
    {
        team: 'Union',
        shield: "/assets/img/futbol-icons/teams/union.png",
        pts: '15',
        pj:'13',
        pg: '4',
        pe: '3',
        pp: '6',
        gf: '12',
        gc: '17',
        dif: '-5'
    },
    {
        team: 'Velez',
        shield: "/assets/img/futbol-icons/teams/velez.png",
        pts: '20',
        pj:'13',
        pg: '5',
        pe: '5',
        pp: '3',
        gf: '17',
        gc: '8',
        dif: '+9'
    }
];