module.exports = tech = [
    {
        title: "Una nena de tres años explica qué es Ethereum usando a Peppa Pig",
        description: "Se llama Lily y es la educadora de criptomonedas más joven del ecosistema en su programa Lily's Show explicó muy sencillo cómo funciona la red Ethereum. “Ethereum es una plataforma de tecnología Blockchain descentralizada y de código abierto“, comentó Lily. Se sabe que Ethereum permite las finanzas descentralizadas, los tokens no fungibles (NFT) y los contratos inteligentes. Allí la pequeña sostiene que fue inventada por Vitalik Buterin. 'Entonces, ¿cómo funciona todo esto? Te lo voy a mostrar con Peppa Pig', dijo pequeña. Peppa representa la criptomoneda nativa de esta cadena de bloques, Ether. Este token 'alimenta' la plataforma, explicó mientras sostenía los juguetes. La mamá y el papá de Peppa representan a los protocolos descentralizados que operan sobre Ethereum, MakerDAO y Uniswap, respectivamente, indicó. 'La mamá de Peppa, que es MakerDAO, puede venir a la casa usando un contrato inteligente', explicó Lily. Luego agregó más juguetes y dijo 'estos son los NFT', son 'el alma de la fiesta'.La nena continuó la transmisión adentrándose en el tema del futuro de Ethereum y la transición a ETH 2.0, que implicará que esta red abandone su actual mecanismo de consenso de prueba de trabajo (PoW) por uno de prueba de participación (PoS). En su video, la pequeña criptoentusiasta también se adentró en los planes de Ethereum para dividir su infraestructura en partes más pequeñas, un proceso que se conoce como sharding o fragmentación.",
        content: "Lily la más pequeña criptoentusiasta que, a través de su programa ‘Lily’s Show’ explica el ecosistema cripto. El último episodio de su show lo dedicó a Ethereum: qué son los NFT, la Blockchain, fueron solo alguno de los conceptos explicados. ",
        urlToImage: "https://media.ambito.com/p/694093c5ff2e2980efd28e8bf6227bfa/adjuntos/239/imagenes/039/366/0039366773/1200x675/smart/pepa-pigjpg.jpg"
    },
    {
        title: "La fintech argentina que busca 22 empleados con sueldos altísimos: $ 350.000 al mes",
        description: "La fintech Wenance busca talento para nuevos proyectos y para dar servicios para España y México",
        content: "El sector de las fintech está en constante movimiento y eso se hace notar también en la demanda de empleo. Wenance, empresa Argentina que otorga créditos mediante sus marcas Mango y Welp. está en plena búsqueda para cubrir 22 posiciones, con salarios que de entre $ 200.000 y $ 350.000. La compañía busca ingenieros backend de Java para proyectos cash in y cash out, onboarding digital, legajo y firma digital, cash in reactivo y dar servicios para diversos países donde opera la fintech, como España y México. También se buscan perfiles para un proyecto de desarrollo de medios de pago. Dentro de su paquete de valor, la fintech ofrece bonos por desempeño, tres ajustes al año por inflación, asesoría en ganancias, prepaga para el empleado y su grupo familiar, tres semanas de vacaciones, día de cumpleaños libre, descuento en gimnasios, accesos a plataformas de capacitación y precios especiales para la compra de notebooks, PC de escritorio, tablets, accesorios y servicios. Además, ofrece la oportunidad de movilidad dentro de la organización. 'Las fintechs estamos abriendo puertas increíbles con el uso de analítica avanzada de datos y de inteligencia artificial. También, con un negocio innovador que apunta a un consumidor que ya no se ve obligado a elegir lo que hay en la góndola sino que puede sacar provecho de servicios personalizados', señala Daniel Zuazaga, Gerente de Desarrollo de Wenance, empresa de origen argentino. La compañía señaló que el sector de IT está en constante búsqueda de talento. Cada año quedan entre 5000 y 10.000 posiciones sin cubrir. Tras la pandemia, la alta demanda de desarrollo de proyectos profundizó la brecha entre profesionales demandados y disponibles.",
        urlToImage: "https://www.cronista.com/files/image/336/336798/60d359d292f44_600_315!.jpg?s=c5d10443772ebb9afcdf99b3310abb71&d=1624464197"
    },
    {
        title: "El Poder Judicial incorporó tecnología para realizar análisis de evidencias digitales",
        description: "Un nuevo software permite extraer información de diferentes dispositivos tecnológicos, la que es utilizada para producir informes periciales.",
        content: "El Gabinete de Informática Forense del Poder Judicial es el organismo encargado de la actividad vinculada al análisis y adquisición de evidencias digitales para aportar elementos probatorios, en procesos que se sustancian en los distintos fueros. Para ello, se adquirieron las herramientas tecnológicas necesarias para efectuar pericias del contenido de dispositivos de almacenamiento, como diferentes tipos de discos (duros, de estado sólido y externos), pendrives, correos electrónicos, medios de almacenamiento y registros de llamadas telefónicas. Asimismo, es materia de análisis el uso dado por los usuarios a dispositivos móviles en una forma más completa, ya que puede accederse a servicios de mensajería y conversaciones en redes sociales. Por otra parte, los profesionales del área brindan asesoramiento técnico a magistrados y funcionarios, respecto al alcance de las pericias peticionadas o a las que pueden realizarse mediante su intervención. En cuanto al requerimiento formal de trabajos, los mismos deben gestionarse a través del  Departamento General de Pericias, del que depende el Gabinete de Informática Forense. En tanto, los operadores judiciales interesados en solicitar este tipo de pericias pueden asesorarse dirigiéndose a la oficina citada, que se encuentra ubicada en el Hall Central del Subsuelo del edificio histórico del Palacio de Tribunales o comunicarse al teléfono (0385) 450-7500i interno. 2554. ",
        urlToImage: "https://www.diariopanorama.com/fotos/notas/2021/10/01/tecnologia-poder-judicial-394572-113752.jpg"
    },
    {
        title: "El mejor software gratis para hacer música en casa",
        description: "Una estación de trabajo digital y una docena de instrumentos virtuales y efectos, todo sin cargo, para explorar tu lado creativo, editar tu podcast o, más importante, jugar con los chicos, que se deslumbrarán con estas tecnologías",
        content: "La vueltas de la vida. Luego de unos treinta años de estar experimentando con toda clase de tecnologías para hacer música, recientemente redescubrí mi primer amor, y parece que es cierto lo que dicen. Porque no solo volví a adoptarlo con el entusiasmo de entonces, sino que hoy es un software gratis. Así que decidí compartirlo con ustedes. Aquí va la historia. Hace casi exactamente tres décadas, cuando llevaba algo así como un año usando una computadora personal, dos cables se unieron en mi mente y tuve una idea. No se rían. Hoy es de lo más normal, pero en ese momento, usar una computadora para hacer música sonaba como algo bastante exótico. Pero allí estaban, mi teclado MIDI y la computadora que había comprado unos meses antes. Nos los aburriré con los detalles técnicos. Al revés que hoy, en esa época tuve que comprar una plaqueta especial para darle a mi PC la capacidad de hablar con un instrumento musical. Una placa MIDI, para ser exactos. Pero aun después de haber conseguido establecer el vínculo de hardware, faltaba todavía una pieza fundamental: el software. Uno tiende a olvidar este detalle, incluso hoy. Te comprás la notebook y después de desembalarla y ponerla en marcha te das cuenta de que no trae Office. No, no trae. Hay que pagarlo aparte. Pista: podés usar LibreOffice, que no tiene costo. Treinta años atrás, el software era una sustancia aún más esquiva. En todo caso, y después de leer bastante (en revistas especializadas, no había conexiones públicas a internet todavía) y de preguntar en los negocios del ramo (qué viejo sonó eso), conseguí un programa llamado Cakewalk. Cakewalk era un secuenciador de una compañía estadounidense llamada Twelve Tones. ¿Un secuenciador? ¿Y qué vendría a ser eso, exactamente? Para entenderlo, hay que mirar el lenguaje MIDI, que por fortuna no solo es público, sino, además, muy simple. Dejando de lado una serie de detalles, MIDI (siglas en inglés de Interfaz Digital para Instrumentos Musicales) permite comunicar los eventos típicos de la ejecución de un instrumento. Por ejemplo, que una tecla fue pulsada, que se la soltó, con qué fuerza se la presionó (en la jerga eso se llama velocidad), y otras cosas por el estilo. Por supuesto, los eventos se comunican y registran de forma enteramente digital; es decir, son numéricos. La clase de materia con la que las computadoras se llevan mejor. En este contexto, una pieza para piano sería una secuencia de eventos MIDI. Uno toca en un teclado MIDI y el instrumento envía cada evento (es decir, lo que nosotros tocamos) a una computadora, que registra esa secuencia usando un programa llamado –ahora es obvio– secuenciador.",
        urlToImage: "https://resizer.glanacion.com/resizer/Zi3ROynyAYJd182lW-r_dIY6PM0=/768x0/filters:quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/TIX5TK4TZBB6JJEYHCPDIE77BY.jpg"
    },
    {
        title: "La función secreta de iOS 15 que Apple no reveló en su último evento",
        description: "La nueva versión del sistema operativo de iPhone permite cambiar el tamaño de letra de cada app.",
        content: "En el software del iPhone siempre hay alguna sorpresa escondida. A una semana del lanzamiento del iOS 15 -sin contar la beta lanzada en junio- siempre queda alguna perla que se va revelando a medida que comienza a extenderse la nueva versión del sistema operativo. Desde hace tiempo es posible cambiar el tamaño del texto desde los ajustes del iPhone, pero esto se aplica a todas y cada una de las aplicaciones del sistema, por lo que al final puede no resultar todo lo práctico que uno desearía. La novedad es que cada funcionalidad muestre una tipografía propia, es decir, que los contactos tengan un tamaña de letra específico y los caracteres de la agenda sean más pequeños y redondeados, ahora es posible. Sin embargo, este método no permite modificar la fuente de la interfaz del sistema, es decir, la medida sólo aplica a ajustes a determinadas aplicaciones. Lo que sí es posible hacer es varios arreglos en el propio texto, desde los ajustes de accesibilidad. También se puede cambiar ajustes como que el texto esté en negrita, sea más grande, aumentar el contraste. Son opciones pensadas para una mejor accesibilidad, pero cualquier usuario las puede modificar. Para conseguirlo, como explican en La manzana mordida, desde Ajustes elegir Centro de control y buscar la opción Tamaño del texto y añadirla con el botón ‘+’ que aparece a la izquierda en color verde. Una vez hecho esto se tendrá acceso desde el correspondiente panel de iOS. Tan solo bastará con abrir la app en cuestión que deseas modificar y acceder a esta función. Al deslizar el debo sobre la tipografía, se puede aumentar el tamaño de letra o volverla más pequeña. En la parte inferior se puede determinar si ese ajuste se aplica para esa app o si uno quiere que cambie para todo el sistema.",
        urlToImage: "https://images.clarin.com/2021/09/20/la-funcion-secreta-del-ios___sZmKkwEsj_1200x630__1.jpg"
    }
]